services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: .
